---
- hosts: SSH_key
  become_user: root
  tasks:
  - name: Create .ssh folder for {{ user_name }}
    file:
      path: ~/.ssh
      state: directory
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0700

  - name: Create authorized_keys file (public key) for {{ user_name }}
    copy:
      src: /home/longdiep/tiendinh_pubkey
      dest: ~/.ssh/authorized_keys
      owner: '{{ user_name }}'
      group: '{{ user_name }}'
      mode: 0600
